steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/palindrome-image:tag1', '.' ]
    #args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/palindrome-image:tag1', '.' ]
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/images/palindrome-image:tag1'
  #- 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/palindrome-image:tag1'